import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardArrowDown, Clock3 } from 'lucide-react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { Loading } from '../components/Loading';
import { api, ApiError } from '../lib/api';
import { formatCurrency, formatDate } from '../lib/format';
import type { MovementDetail } from '../types';

export function MovementDetailPage() {
  const { id } = useParams(); const location = useLocation(); const [data, setData] = useState<MovementDetail | null>(null); const [error, setError] = useState('');
  useEffect(() => { api<MovementDetail>(`/movements/${id}`).then(setData).catch(e => setError(e instanceof ApiError ? e.message : 'Erro ao carregar movimentação.')); }, [id]);
  if (!data && !error) return <Loading label="Carregando movimentação..." />;
  if (error) return <div className="card border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>;
  if (!data) return null;
  const pending = data.items.reduce((s, i) => s + Math.max(0, i.quantityOut - i.quantityReturned), 0);
  const created = (location.state as any)?.created;
  const returnSuccess = Boolean((location.state as any)?.returnSuccess);
  return <div className="space-y-5">{created && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-700"><CheckCircle2 className="h-5 w-5" />Saída {created} registrada com sucesso.</div>}{returnSuccess && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-700"><CheckCircle2 className="h-5 w-5" />Devolução registrada com sucesso.</div>}<div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><span className="font-mono text-sm font-bold text-slate-500">{data.movementCode}</span><MovementStatus status={data.status} /></div><h2 className="mt-1 text-2xl font-bold tracking-tight">{data.type === 'RENTAL' ? 'Aluguel' : 'Saída externa'}</h2></div>{pending > 0 && data.status !== 'CANCELLED' && <Link to={`/devolucoes/${data.id}`} className="btn-primary"><ClipboardArrowDown className="h-4 w-4" />Registrar devolução ({pending})</Link>}</div><section className="card p-5 sm:p-6"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><Info label="Responsável" value={data.responsibleName} /><Info label="Destino" value={data.destination} /><Info label="Saída" value={formatDate(data.checkoutAt, true)} /><Info label="Retorno previsto" value={formatDate(data.expectedReturnAt, true)} />{data.projectClient && <Info label="Projeto/cliente" value={data.projectClient} />}{data.renterName && <Info label="Locatário" value={data.renterName} />}{data.rentalValue != null && <Info label="Valor" value={formatCurrency(data.rentalValue)} />}</div>{data.notes && <p className="mt-5 border-t border-slate-200 pt-4 text-sm text-slate-600">{data.notes}</p>}</section><section className="card overflow-hidden"><div className="border-b border-slate-200 p-4 sm:px-5"><h3 className="font-bold">Itens da movimentação</h3><p className="text-sm text-slate-500">{pending} unidade(s) ainda pendente(s).</p></div><div className="divide-y divide-slate-100">{data.items.map(i => { const left = Math.max(0, i.quantityOut - i.quantityReturned); return <div key={i.id} className="flex items-center gap-3 p-4 sm:px-5"><div className="min-w-0 flex-1"><div className="font-mono text-xs font-bold text-slate-500">{i.internalCode}</div><div className="truncate font-semibold">{i.name}</div><div className="text-xs text-slate-500">Saiu {i.quantityOut} · devolvido {i.quantityReturned}</div></div><div className={`rounded-xl px-3 py-2 text-center ${left > 0 ? 'bg-amber-50 text-amber-800' : 'bg-emerald-50 text-emerald-700'}`}><div className="text-lg font-bold">{left}</div><div className="text-[10px] font-bold uppercase">{left > 0 ? 'pendente' : 'ok'}</div></div></div>; })}</div></section></div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><div className="text-xs font-medium text-slate-500">{label}</div><div className="mt-1 font-semibold text-slate-900">{value}</div></div>; }
function MovementStatus({ status }: { status: MovementDetail['status'] }) { const cls = status === 'OVERDUE' ? 'bg-red-50 text-red-700' : status === 'RETURNED' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800'; const icon = status === 'OVERDUE' ? <AlertTriangle className="h-3 w-3" /> : status === 'RETURNED' ? <CheckCircle2 className="h-3 w-3" /> : <Clock3 className="h-3 w-3" />; const label = { OPEN: 'Aberta', PARTIALLY_RETURNED: 'Devolução parcial', RETURNED: 'Devolvida', OVERDUE: 'Atrasada', CANCELLED: 'Cancelada' }[status]; return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-bold ${cls}`}>{icon}{label}</span>; }
